'use strict';

// Tsv Formatter — Tab-separated values for ETL pipeline import
// Auto-generated by IntelliMatch MCP Server

const DELIMITER = '\t';

function formatRows(records) {
  if (!records.length) return '';
  const headers = Object.keys(records[0]);
  const lines   = [headers.join(DELIMITER)];
  for (const rec of records) {
    lines.push(headers.map(h => String(rec[h] == null ? '' : rec[h])).join(DELIMITER));
  }
  return lines.join('\n');
}

function formatLedger(records)    { return formatRows(records); }
function formatStatement(records) { return formatRows(records); }

module.exports = { formatLedger, formatStatement, ext: 'tsv' };
